### ISSUE TITLE
Send notification to subscribers upon adding new Shared URL

### ISSUE THREAD

**Issue by gammaw** [EM-GUIDE/em-guide-tool#23]
Email template: 

[MAG] has just shared [MAG]'s article: [Article name]

**Comment by revnandi** [comment]
Maybe the magazines should be added to the urls component so when adding a shared url the magazine is linked to that url.

**Comment by gammaw** [comment]
Good idea! And we could define for each magazine the corresponding user email addresses. 

It's important though that filling the magazine with the shared URL is a mandatory action.

**Comment by gammaw** [comment]
Updated spec: 

- When a new SharedURL entry is added, send email notification to all subscribers (of the article);
- Subject of email: "EM GUIDE: New share on "ARTICLE TITLE"
- Email body: 
   - Print the newly added SharedURL entry;
   - Embed "Open article" button;
